### ISSUE TITLE
Bug when no path can be assigned and no next_ATC available

### ISSUE THREAD

**Issue by hudluft** [LGooyaers/OSSAR#16]
The simulation crashes with:
next_atc = plane.op[0].par['next_atc']
KeyError: 'next_atc'

This might happen because an aircraft gets to the handoff_threshold, but has no next_atc assigned since there is no path available.
We can either fix this through the command status, or just say that when there is no next_atc, keep the current atc and hold.

**Comment by LGooyaers** [comment]
Fixed by introducing a stop parameter for the aircraft when there is no goal/next_atc
